In [2]:
from sklearn.datasets import load_iris

iris_dataset = load_iris()

X = iris_dataset['data']
y = iris_dataset['target']

print(X)
print(y)

nome_das_classes = iris_dataset.target_names

#print(nome_das_classes)
#print(iris_dataset.feature_names)
#print(type(iris_dataset))
#print(iris_dataset)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Criando um Pipeline

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier

MLP_pipeline = Pipeline(steps=[
  ("Normalizacao", MinMaxScaler()),
  ("MLP", MLPClassifier())
])

Executando o mesmo pipeline multiplas vezes

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
N = 10
acuracias = list()
for i in range(N):
    X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, shuffle=True)
    MLP_pipeline.fit(X_treino, y_treino)
    ac_i = MLP_pipeline.score(X_teste, y_teste)
    acuracias.append(ac_i)

print("Acurácia:")
print(acuracias)
print(f"Media: {round(np.mean(acuracias) * 100, 1)}%")
print(f"Desvio padrão: {round(np.std(acuracias) * 100, 1)}%")

Usando cross_val_score

In [ ]:
from sklearn.model_selection import cross_val_score
acuracias = cross_val_score(MLP_pipeline, X, y, cv=5)
print("Acurácias:", acuracias)
print("Acurácia final:", np.mean(acuracias))
print("Desvio Padrão:", np.std(acuracias))

# Exemplo da definição do tipo de métrica para retorno
acuraciasB = cross_val_score(MLP_pipeline, X, y, cv=5, scoring="balanced_accuracy")
print("\nAcurácias Balanceadas:", acuraciasB)
print("Acurácia Balanceada Final:", np.mean(acuraciasB))
print("Desvio Padrão:", np.std(acuraciasB))

Usando cross_validate

In [ ]:
from sklearn.model_selection import cross_validate
nome_metricas = ['accuracy', 'precision_macro', 'recall_macro']
metricas = cross_validate(MLP_pipeline, X, y, cv=5, scoring=nome_metricas)
for met in metricas:
    print(f"- {met}:")
    print(f"-- {metricas[met]}")
    print(f"-- {np.mean(metricas[met])} +- {np.std(metricas[met])}\n")

Gerando predições via cross_val_predict

In [ ]:
from sklearn.model_selection import cross_val_predict
pred = cross_val_predict(MLP_pipeline, X, y, cv=5)
print(pred)

Uso do GridSearchCV

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler


# Divisão dos dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Definição do Pipeline
pipeline = Pipeline([
    ('normalizacao', MinMaxScaler()),      # Escalonamento dos dados
    ('mlp', MLPClassifier(max_iter=5000))  # Classificador MLP
])

# Parâmetros para o GridSearchCV
param_grid = {
    'mlp__hidden_layer_sizes': [(10,), (20,), (10,10)], # Configurações das camadas ocultas
    'mlp__activation': ['relu', 'tanh'],                 # Funções de ativação
    'mlp__solver': ['adam', 'sgd'],                      # Otimizadores
    'mlp__learning_rate': ['constant', 'adaptive']       # Taxa de aprendizado
}

# Criação do GridSearchCV
grid_search = GridSearchCV(pipeline, param_grid, cv=3)

# Ajuste do modelo
grid_search.fit(X_train, y_train)

# Melhor combinação de hiperparâmetros
print(f"Melhores parâmetros: {grid_search.best_params_}")

# Avaliação do modelo
score = grid_search.score(X_test, y_test)
print(f"Acurácia no conjunto de teste: {score}")


Testando com o GridSearchCV sem Pipeline - Ideal para pequenas grades de hiperparâmetros, pois testa todas as combinações possíveis.

In [ ]:
# Definir a grade de hiperparâmetros
param_grid = {
    'hidden_layer_sizes': [(10,), (20,)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate': ['constant', 'adaptive']
}

# Configurar GridSearchCV
grid_search = GridSearchCV(MLPClassifier(max_iter=5000), param_grid, cv=3)
grid_search.fit(X_train, y_train)

# Exibir os melhores parâmetros e desempenho
print("Melhores parâmetros:", grid_search.best_params_)
print("Acurácia:", grid_search.best_score_)

Testando com o RandomizedSearchCV sem Pipeline - Mais eficiente em termos de tempo para grades grandes, pois testa apenas uma amostra aleatória das combinações.

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform

# Definir o espaço de busca aleatória
param_dist = {
    'hidden_layer_sizes': [(10,), (20,)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate': ['constant', 'adaptive']
}

# Configurar RandomizedSearchCV
random_search = RandomizedSearchCV(MLPClassifier(max_iter=5000), param_dist, cv=3, n_iter=20)
random_search.fit(X_train, y_train)

# Exibir os melhores parâmetros encontrados
print("Melhores parâmetros:", random_search.best_params_)
print("Acurácia:", random_search.best_score_)